steps:
  # Install
  # - name: node:12
  #   entrypoint: npm
  #   args: ['i']
  # Test
  # - name: node:12
  #   entrypoint: npm
  #   args: ['test']
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/node-worker:$COMMIT_SHA',
      '-f', 'infra/Dockerfile',
      '.'
    ]
  # Tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      'gcr.io/$PROJECT_ID/node-worker:$COMMIT_SHA',
      'gcr.io/$PROJECT_ID/node-worker:${_ENV}',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      'gcr.io/$PROJECT_ID/node-worker:${_ENV}',
      'gcr.io/$PROJECT_ID/node-worker:latest',
    ]
  # Deploy
  - name: 'gcr.io/$PROJECT_ID/helm'
    dir: 'infra/helm'
    args: [
      'upgrade',
      '--install',
      '-f', 'values.yaml',
      '--set', 'image.tag=$COMMIT_SHA',
      'node-worker',
      '.'
    ]
    env: [
      'CLOUDSDK_COMPUTE_ZONE=${_ZONE}',
      'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
    ]
images: [
  'gcr.io/$PROJECT_ID/node-worker:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/node-worker:${_ENV}',
  'gcr.io/$PROJECT_ID/node-worker:latest'
]
options:
  machineType: N1_HIGHCPU_8
timeout: 1200s